controllers/NewsController.php
<?php

    namespace app\controllers;

    use yii\web\UploadedFile;
    use app\models\UploadForm;
    use Yii;
    use app\models\News;
    use yii\data\ActiveDataProvider;
    use yii\web\Controller;
    use yii\web\NotFoundHttpException;
    use yii\filters\VerbFilter;

    /**
     * NewsController implements the CRUD actions for News model.
     */
    class NewsController extends Controller
    {
        /**
         * @inheritdoc
         */
        public function behaviors()
        {
            return [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ];
        }

        /**
         * Lists all News models.
         * @return mixed
         */
        public function actionIndex()
        {
            $news = new News();
            return $this->render('index', [
                'news' => News::find()->all(),
            ]);
        }

        /**
         * Displays a single News model.
         * @param integer $id
         * @return mixed
         * @throws NotFoundHttpException if the model cannot be found
         */
        public function actionView($id)
        {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }

        /**
         * Creates a new News model.
         * If creation is successful, the browser will be redirected to the 'view' page.
         * @return mixed
         */
        public function actionCreate()
        {
            $model = new News();


            $this->handleNewsSave($model);

            return $this->render('create', [
                'model' => $model
            ]);
        }

        /**
         * Updates an existing News model.
         * If update is successful, the browser will be redirected to the 'view' page.
         * @param integer $id
         * @return mixed
         * @throws NotFoundHttpException if the model cannot be found
         */
        public function actionUpdate($id)
        {
            $model = $this->findModel($id);

            $this->handleNewsSave($model);

            return $this->render('update', [
                'model' => $model,
            ]);
        }


        public function actionDelete($id)
        {

            if($this->findModel($id)->delete())
            {
                return true;
            }

            return false;
        }

        /**
         * Finds the News model based on its primary key value.
         * If the model is not found, a 404 HTTP exception will be thrown.
         * @param integer $id
         * @return News the loaded model
         * @throws NotFoundHttpException if the model cannot be found
         */
        protected function findModel($id)
        {
            if (($model = News::findOne($id)) !== null) {
                return $model;
            }

            throw new NotFoundHttpException('The requested page does not exist.');
        }

        protected function handleNewsSave(News $model)
        {
            if ($model->load(Yii::$app->request->post()))
            {
                $model->image = UploadedFile::getInstance($model, 'image');

                if ($model->validate())
                {
                    if ($model->image)
                    {
                        $filePath = 'uploads/' . $model->image->baseName . time() . '.' . $model->image->extension;
                        if ($model->image->saveAs($filePath))
                        {
                            $model->image = $filePath;
                        }
                    }

                    if ($model->save(false))
                    {
                        return $this->redirect(['view', 'id' => $model->id]);
                    }
                }
            }
        }

    }

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Новости',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Главная', 'url' => ['/news/index']],
            ['label' => 'Добавить новость', 'url' => ['/news/create']]

        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<script>
    jQuery(document).ready(function ($) {
        $('.delete').click(function () {
            var id = $(this).data('id');

            $.ajax({
                method: "POST",
                url: "<?=\Yii::getAlias('@web');?>/news/delete/?id="+id,
            })
                .done(function( msg ) {
                    if(msg == true){
                        $('#news'+id).hide();
                    }else{
                        console.log(msg);
                        alert("Не могу удалить эту новость, загляни в консоль");
                    }
                });
        });
    });
</script>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>