models/News.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property string $image
 */
class News extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'description', 'image'], 'required', 'message' => '{attribute} не может быть пустым'],
            [['description'], 'string'],
            [['title'], 'string', 'max' => 255],
            [['image'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'description' => 'Описание',
            'image' => 'Изображение',
        ];
    }

}

controllers/NewsController.php
<?php

    namespace app\controllers;

    use yii\web\UploadedFile;
    use app\models\UploadForm;
    use Yii;
    use app\models\News;
    use yii\data\ActiveDataProvider;
    use yii\web\Controller;
    use yii\web\NotFoundHttpException;
    use yii\filters\VerbFilter;

    /**
     * NewsController implements the CRUD actions for News model.
     */
    class NewsController extends Controller
    {
        /**
         * @inheritdoc
         */
        public function behaviors()
        {
            return [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ];
        }

        /**
         * Lists all News models.
         * @return mixed
         */
        public function actionIndex()
        {
            $news = new News();
            return $this->render('index', [
                'news' => News::find()->all(),
            ]);
        }

        /**
         * Displays a single News model.
         * @param integer $id
         * @return mixed
         * @throws NotFoundHttpException if the model cannot be found
         */
        public function actionView($id)
        {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }

        /**
         * Creates a new News model.
         * If creation is successful, the browser will be redirected to the 'view' page.
         * @return mixed
         */
        public function actionCreate()
        {
            $model = new News();


            $this->handleNewsSave($model);

            return $this->render('create', [
                'model' => $model
            ]);
        }

        /**
         * Updates an existing News model.
         * If update is successful, the browser will be redirected to the 'view' page.
         * @param integer $id
         * @return mixed
         * @throws NotFoundHttpException if the model cannot be found
         */
        public function actionUpdate($id)
        {
            $model = $this->findModel($id);

            $this->handleNewsSave($model);

            return $this->render('update', [
                'model' => $model,
            ]);
        }


        public function actionDelete($id)
        {

            if($this->findModel($id)->delete())
            {
                return true;
            }

            return false;
        }

        /**
         * Finds the News model based on its primary key value.
         * If the model is not found, a 404 HTTP exception will be thrown.
         * @param integer $id
         * @return News the loaded model
         * @throws NotFoundHttpException if the model cannot be found
         */
        protected function findModel($id)
        {
            if (($model = News::findOne($id)) !== null) {
                return $model;
            }

            throw new NotFoundHttpException('The requested page does not exist.');
        }

        protected function handleNewsSave(News $model)
        {
            if ($model->load(Yii::$app->request->post()))
            {
                $model->image = UploadedFile::getInstance($model, 'image');

                if ($model->validate())
                {
                    if ($model->image)
                    {
                        $filePath = 'uploads/' . $model->image->baseName . time() . '.' . $model->image->extension;
                        if ($model->image->saveAs($filePath))
                        {
                            $model->image = $filePath;
                        }
                    }

                    if ($model->save(false))
                    {
                        return $this->redirect(['view', 'id' => $model->id]);
                    }
                }
            }
        }

    }

views/news/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\News */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="news-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'image')->fileInput(); ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/news/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = 'Добавить новость';
$this->params['breadcrumbs'][] = ['label' => 'Новости', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/news/index.php
<?php

    use yii\helpers\Html;


    /* @var $this yii\web\View */

    $this->title = 'Новости';
    $this->params['breadcrumbs'][] = $this->title;


?>
<div class="news-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Добавить новость', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php
        if (empty($news)) {
            echo 'Новостей нету';
        }

        /** @var array $news */
        foreach ($news as $item) {
            ?>

            <div class="row" id="news<?= $item->id ?>">

                <div class="col-md-12 ">
                    <h1><a href="<?= \yii\helpers\Url::to(['news/view', 'id' => $item->id]) ?>"><?= $item->title ?></a></h1>
                    <img width="200px" style="margin: 0 5px 5px 0;"
                         src="<?= \Yii::getAlias('@web') . '/' . $item->image ?>" alt="<?= $item->title ?>"
                         class="pull-left img-responsive thumb margin10 img-thumbnail">
                    <input type="button" class="btn btn-danger delete pull-right" data-id="<?= $item->id ?>"
                           value="Удалить">

                    <article>
                        <p><?= \yii\helpers\StringHelper::truncate($item->description, 150,
                                '<a class="btn btn-blog " href="' . \yii\helpers\Url::to([
                                    'news/view',
                                    'id' => $item->id
                                ]) . '">Читать далее</a>'); ?>
                        </p>
                    </article>

                </div>
            </div>


            <?php
        }
    ?>


</div>

views/news/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = 'редактирование: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Новости', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="news-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/news/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Новости', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вый действительно хотите удалить эту новость?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'description:ntext',
            [
                'attribute' => 'image',
                'format' => 'html',
                'value' => function($model){
                    return '<img width="200px" src="'.\Yii::getAlias('@web').'/'.$model->image.'" >';
                }
            ],
        ],
    ]) ?>

</div>